apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
  labels:
    app: my-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-spring-boot-app
  template:
    metadata:
      labels:
        app: my-spring-boot-app
    spec:
      containers:
      - name: my-spring-boot-app
        image: thouraya/my-spring-boot-app:latest  # Remplacez par l'image de votre application
        ports:
        - containerPort: 8080  # Remplacez par le port que votre application Spring Boot écoute
